#include "ATHYG.h"

#include "../../core/utils/Utils.h"

#include <array>
#include <cstddef>
#include <string>

namespace LouiEriksson::Engine::Spatial {
	
	ATHYG::V1::V1(const std::array<std::string, 23>& _values) :
		 id      (Utils::TryParse<size_t     >(_values[ 0])),
		 tyc     (Utils::TryParse<std::string>(_values[ 1])),
		 gaia    (Utils::TryParse<size_t     >(_values[ 2])),
		 hyg     (Utils::TryParse<size_t     >(_values[ 3])),
		 hip     (Utils::TryParse<size_t     >(_values[ 4])),
		 hd      (Utils::TryParse<size_t     >(_values[ 5])),
		 hr      (Utils::TryParse<size_t     >(_values[ 6])),
		 gl      (Utils::TryParse<std::string>(_values[ 7])),
		 bayer   (Utils::TryParse<std::string>(_values[ 8])),
		 flam    (Utils::TryParse<std::string>(_values[ 9])),
		 con     (Utils::TryParse<std::string>(_values[10])),
		 proper  (Utils::TryParse<std::string>(_values[11])),
		 ra      (Utils::TryParse<double     >(_values[12])),
		 dec     (Utils::TryParse<double     >(_values[13])),
		 pos_src (Utils::TryParse<std::string>(_values[14])),
		 dist    (Utils::TryParse<double     >(_values[15])),
		 x0      (Utils::TryParse<double     >(_values[16])),
		 y0      (Utils::TryParse<double     >(_values[17])),
		 z0      (Utils::TryParse<double     >(_values[18])),
		 dist_src(Utils::TryParse<std::string>(_values[19])),
		 mag     (Utils::TryParse<double     >(_values[20])),
		 absmag  (Utils::TryParse<double     >(_values[21])),
		 mag_src (Utils::TryParse<std::string>(_values[22])) {}
	
	ATHYG::V2::V2(const std::array<std::string, 33>& _values) :
		id       (Utils::TryParse<size_t     >(_values[ 0])),
		tyc      (Utils::TryParse<std::string>(_values[ 1])),
		gaia     (Utils::TryParse<size_t     >(_values[ 2])),
		hyg      (Utils::TryParse<size_t     >(_values[ 3])),
		hip      (Utils::TryParse<size_t     >(_values[ 4])),
		hd       (Utils::TryParse<size_t     >(_values[ 5])),
		hr       (Utils::TryParse<size_t     >(_values[ 6])),
		gl       (Utils::TryParse<std::string>(_values[ 7])),
		bayer    (Utils::TryParse<std::string>(_values[ 8])),
		flam     (Utils::TryParse<std::string>(_values[ 9])),
		con      (Utils::TryParse<std::string>(_values[10])),
		proper   (Utils::TryParse<std::string>(_values[11])),
		ra       (Utils::TryParse<double     >(_values[12])),
		dec      (Utils::TryParse<double     >(_values[13])),
		pos_src  (Utils::TryParse<std::string>(_values[14])),
		dist     (Utils::TryParse<double     >(_values[15])),
		x0       (Utils::TryParse<double     >(_values[16])),
		y0       (Utils::TryParse<double     >(_values[17])),
		z0       (Utils::TryParse<double     >(_values[18])),
		dist_src (Utils::TryParse<std::string>(_values[19])),
		mag      (Utils::TryParse<double     >(_values[20])),
		absmag   (Utils::TryParse<double     >(_values[21])),
		mag_src  (Utils::TryParse<std::string>(_values[22])),
		rv       (Utils::TryParse<double     >(_values[23])),
		rv_src   (Utils::TryParse<std::string>(_values[24])),
		pm_ra    (Utils::TryParse<double     >(_values[25])),
		pm_dec   (Utils::TryParse<double     >(_values[26])),
		pm_src   (Utils::TryParse<double     >(_values[27])),
		vx       (Utils::TryParse<double     >(_values[28])),
		vy       (Utils::TryParse<double     >(_values[29])),
		vz       (Utils::TryParse<double     >(_values[30])),
		spect    (Utils::TryParse<double     >(_values[31])),
		spect_src(Utils::TryParse<std::string>(_values[32])) {}
	
	ATHYG::V3::V3(const std::array<std::string, 34>& _values) :
		id       (Utils::TryParse<size_t     >(_values[ 0])),
		tyc      (Utils::TryParse<std::string>(_values[ 1])),
		gaia     (Utils::TryParse<size_t     >(_values[ 2])),
		hyg      (Utils::TryParse<size_t     >(_values[ 3])),
		hip      (Utils::TryParse<size_t     >(_values[ 4])),
		hd       (Utils::TryParse<size_t     >(_values[ 5])),
		hr       (Utils::TryParse<size_t     >(_values[ 6])),
		gl       (Utils::TryParse<std::string>(_values[ 7])),
		bayer    (Utils::TryParse<std::string>(_values[ 8])),
		flam     (Utils::TryParse<std::string>(_values[ 9])),
		con      (Utils::TryParse<std::string>(_values[10])),
		proper   (Utils::TryParse<std::string>(_values[11])),
		ra       (Utils::TryParse<double     >(_values[12])),
		dec      (Utils::TryParse<double     >(_values[13])),
		pos_src  (Utils::TryParse<std::string>(_values[14])),
		dist     (Utils::TryParse<double     >(_values[15])),
		x0       (Utils::TryParse<double     >(_values[16])),
		y0       (Utils::TryParse<double     >(_values[17])),
		z0       (Utils::TryParse<double     >(_values[18])),
		dist_src (Utils::TryParse<std::string>(_values[19])),
		mag      (Utils::TryParse<double     >(_values[20])),
		absmag   (Utils::TryParse<double     >(_values[21])),
		ci       (Utils::TryParse<double     >(_values[22])),
		mag_src  (Utils::TryParse<std::string>(_values[23])),
		rv       (Utils::TryParse<double     >(_values[24])),
		rv_src   (Utils::TryParse<std::string>(_values[25])),
		pm_ra    (Utils::TryParse<double     >(_values[26])),
		pm_dec   (Utils::TryParse<double     >(_values[27])),
		pm_src   (Utils::TryParse<double     >(_values[28])),
		vx       (Utils::TryParse<double     >(_values[29])),
		vy       (Utils::TryParse<double     >(_values[30])),
		vz       (Utils::TryParse<double     >(_values[31])),
		spect    (Utils::TryParse<double     >(_values[32])),
		spect_src(Utils::TryParse<std::string>(_values[33])) {}
	
} // LouiEriksson::Engine::Spatial